image: Ubuntu  # образ для сборки

stack: jdk 11  # версия JDK

branches:
  only:
    - master  # ветка git

build: off  # будем использовать свой скрипт сборки

install:
  # запускаем SUT (& означает, что в фоновом режиме - не блокируем терминал для запуска тестов)
  - java -jar ./artifacts/app-order.jar &

build_script:
  - chmod +x gradlew # для добавления прав на запуск файла gradlew, добавьте в CI исполнение команды перед тем как использовать этот файл как команду для работы с гредлом
  - ./gradlew test --info  # запускаем тест, флаг --info позволяет выводить больше информации